# usage: ansible-playbook django.yml --extra-vars="user=ssh_user"
---
- hosts: web
  sudo: yes
  vars_files:
    - vars/default.yml
    user: ${user}
    tasks:
      - include: tasks/postgresql.yml
    #handlers:
      #- include: handlers/nginx.yml
