# usage: ansible-playbook nginx_playbook.yml --extra-vars="user=ssh_user django_static_dir=/path/to/static/files"
---
- hosts: web
  sudo: yes
  vars_files:
    - vars/default.yml
  user: ${user}
  tasks:
    - include: tasks/nginx.yml
    - include: tasks/nginx_uwsgi.yml
  handlers:
    - include: handlers/nginx.yml
